### ISSUE TITLE
I can't ban evade with this extension enabled

### ISSUE THREAD

**Issue by UnChaotic** [videochat-extension/videochat-extension#27]
I turn it off and the ban disappears. When its on. The ban shows. 
wtf did you guys do this extension?

**Comment by qrlk** [comment]
it's very unlikely that the extension could cause something like this

you should look for problems on your side, if the extension really caused bans, there would be a lot of noise in our discord

**Comment by UnChaotic** [comment]
Nevermind, it's Microsoft edge not deleting everything properly or its being fingerprinted. Works really well with Brave browser. DUNNO why that is.
